[package]
name = "shin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "sdu"
path = "src/sdu.rs"

[[bin]]
name = "shin"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.65"
binrw = "0.10.0"
clap = { version = "4.0.15", features = ["derive"] }
itertools = "0.10.5"

[profile.release]
debug = true
