[workspace]
members = [
    "shin-derive",
    "shin-core",
    "shin-render",
    "shin-video",
    "shin-tasks",
    "shin-audio",
    "sdu",
    "shin",
    "junk",
]
resolver = "2"

[workspace.dependencies]
glam = "0.23.0"
# git version for GATs
enum-map = { git = "https://github.com/xfix/enum-map.git", rev = "942b6f0fefc41d1e9626f952e60ea88386838e68" }
#enum-map = { path = "/home/dcnick3/git_cloned/enum-map/enum-map" }
wgpu = "0.15.1"
kira = { version = "0.7.1", default-features = false }
egui = { git = "https://github.com/emilk/egui.git", rev = "d15ce22e2edeabf9813ba2965ec64f9c9d62a679" }
image = { version = "0.24.5", default-features = false }
anyhow = "1.0.69"
bevy_utils = "0.10.0"

[profile.release]
debug = true
#lto = 'thin'

# optimize deps
[profile.dev.package."*"]
#opt-level = 2

[profile.release.package.wgpu-core]
# enable debug assertions to keep validations & debug labels
# they are still disabled in `dist` profile used to build the release
debug-assertions = true

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
debug = false
lto = "thin"

[workspace.metadata.release]
shared-version = true
publish = false # can't publish yet because of enum-map git dep
tag-prefix = ""

# Config for 'cargo dist'
[workspace.metadata.dist]
# The preferred cargo-dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.0.5"
# The preferred Rust toolchain to use in CI (rustup toolchain syntax)
rust-toolchain-version = "1.67.1"
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["x86_64-unknown-linux-gnu", "x86_64-apple-darwin", "x86_64-pc-windows-msvc"]
ci = ["github"]
installers = ["shell", "powershell"]
