[workspace]
members = [
    "shin-derive",
    "shin-core",
    "sdu",
    "shin",
    "junk",
]
resolver = "2"

[workspace.dependencies]
# git version for yet unreleased bytemuck feature
cgmath = { git = "https://github.com/rustgd/cgmath.git", rev = "d5e765db61cf9039cb625a789a59ddf6b6ab2337", features = ["bytemuck"] }
# git version for GATs and a map_ref function
enum-map = { git = "https://github.com/DCNick3/enum-map.git", rev = "a04d7e336275c5d3796dff157b756af2dab268d7" }

[profile.release]
debug = true
lto = 'thin'

# optimize deps
[profile.dev.package."*"]
#opt-level = 2