[workspace]
members = [
    "shin-derive",
    "shin-core",
    "sdu",
    "shin",
]

resolver = "2"

[profile.release]
debug = true
lto = 'thin'

# optimize deps
[profile.dev.package."*"]
opt-level = 2