[package]
name = "junk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.7.0"
once_cell = "1.16.0"
binrw = "0.10.0"
stl_io = "0.7.0"