[package]
name = "shin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
shin-core = { path = "../shin-core" }

anyhow = "1.0.65"
async-trait = "0.1.58"
futures = "0.3.25"
smallvec = "1.10.0"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
copyless = "0.1.5"
arrayvec = "0.7.2"
bytes = "1.2.1"
cfg-if = "1.0.0"

winit = "0.27.5"
wgpu = "0.14.0"
wrld = "1.0.0"

# git version for yet unreleased bytemuck feature
cgmath = { git = "https://github.com/rustgd/cgmath.git", rev = "d5e765db61cf9039cb625a789a59ddf6b6ab2337", features = ["bytemuck"] }
bytemuck = { version = "1.12.3", features = ["derive"] }
image = "0.24.5"

# TODO: this is kinda heavy... We can definitely live without all the ECS code
bevy_time = "0.9.1"
bevy_utils = "0.9.1"

pollster = "0.2.5"

num-derive = "0.3.3"
num-traits = "0.2.15"
enum-map = "2.4.1"
derive_more = "0.99.17"
enum_dispatch = "0.3.8"
itertools = "0.10.5"

[features]
default = []
