[package]
name = "shin"
version = "0.4.0"
edition = "2021"
description = "A visual novel engine used by some entergram games"
repository = "https://github.com/DCNick3/shin"
license = "MPL-2.0"
authors = ["DCNick3"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
shin-core = { path = "../shin-core" }
shin-render = { path = "../shin-render" }
shin-derive = { path = "../shin-derive" }
shin-tasks = { path = "../shin-tasks" }
shin-audio = { path = "../shin-audio" }
shin-video = { path = "../shin-video" }

anyhow = { workspace = true }
async-trait = "0.1.58"
futures = "0.3.25"
smallvec = "1.10.0"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
arrayvec = "0.7.2"
bytes = "1.2.1"
cfg-if = "1.0.0"
clap = { version = "4.1.4", features = ["derive"] }
clap-num = "1.0.2"
dirs-next = "2.0.0"

winit = "0.28.1"
wgpu = { workspace = true }
# git version for integer overflow fix https://github.com/nical/etagere/pull/21
etagere = { git = "https://github.com/DCNick3/etagere", rev = "53c7ba67256408af78b66909bad7bb905648ec97" }

glam = { workspace = true, features = [
    # "scalar-math" disables the 16-byte alignment requirement for some types
    # this is required for bytemuck to work
    "bytemuck", "scalar-math"
] }
bytemuck = { version = "1.12.3", features = ["derive"] }
image = { workspace = true, default-features = false, features = [] }

# Theese part of bevy does not depend on ECS or the reflection, so it's not a big problem to use them
bevy_utils = "0.9.1"

pollster = "0.3.0"

num-derive = "0.3.3"
num-traits = "0.2.15"
enum-map = { workspace = true }
derive_more = "0.99.17"
enum_dispatch = "0.3.8"
strum = "0.24.1"
anymap = "1.0.0-beta.2"
derivative = "2.2.0"
serde = "1.0.152"

itertools = "0.10.5"
once_cell = "1.16.0"
petitset = "0.2.1"

# egui used for debug overlays
# git version for wgpu 0.15 support
egui = { workspace = true }
egui-wgpu = { git = "https://github.com/emilk/egui.git", rev = "d15ce22e2edeabf9813ba2965ec64f9c9d62a679", features = [] }
usvg = "0.29.0"

# kira for audio output
kira = { workspace = true }

[features]
default = []

[package.metadata.release]
# this crate is not ready for publishing yet
# (it has git dependencies)
publish = false
