[package]
name = "shin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
shin-core = { path = "../shin-core" }
shin-derive = { path = "../shin-derive" }

anyhow = "1.0.65"
async-trait = "0.1.58"
futures = "0.3.25"
smallvec = "1.10.0"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
copyless = "0.1.5"
arrayvec = "0.7.2"
bytes = "1.2.1"
cfg-if = "1.0.0"

winit = "0.27.5"
wgpu = "0.14.0"
wrld = "1.0.0"

cgmath = { workspace = true, features = ["bytemuck"] }
bytemuck = { version = "1.12.3", features = ["derive"] }
image = "0.24.5"

# TODO: this is kinda heavy... We can definitely live without all the ECS code
bevy_time = "0.9.1"
bevy_utils = "0.9.1"
bevy_tasks = "0.9.1"

pollster = "0.2.5"

num-derive = "0.3.3"
num-traits = "0.2.15"
enum-map = { workspace = true }
derive_more = "0.99.17"
enum_dispatch = "0.3.8"
itertools = "0.10.5"
# git version for integer overflow fix https://github.com/nical/etagere/pull/21
etagere = { git = "https://github.com/DCNick3/etagere", rev = "53c7ba67256408af78b66909bad7bb905648ec97" }
lru = "0.9.0"
strum = "0.24.1"
typemap = "0.3.3"
once_cell = "1.16.0"
petitset = "0.2.1"

# egui used for debug overlays
egui = { version = "0.20.1", features = [] }
egui_extras = { version = "0.20.0", features = ["svg"] }
egui-wgpu = { version = "0.20.0", features = [] }
usvg = "0.28.0"

# kira for audio output
kira = { version = "0.7.1", default-features = true, features = ["cpal"] }

[features]
default = []
