[package]
name = "shin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
shin-core = { path = "../shin-core" }

anyhow = "1.0.65"
async-trait = "0.1.58"
futures = "0.3.25"
smallvec = "1.10.0"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
bevy = "0.8.1"
bevy_prototype_lyon = "0.6.0"
copyless = "0.1.5"

[features]
default = [
    "bevy/dynamic"
]
